export default function Contract() {
    return(
        <div className="contractDiv whiteBack">
            <h4>MANIFIESTAN Y ACUERDAN:</h4>
            <p>Tanto GLOVO como el PARTNER serán denominados, conjuntamente, como las Partes y cada uno de ellos, individualmente, una Parte. Las Partes manifiestan mutuamente tener capacidad legal para obligarse y a tal efecto,</p>
            <p>I.     Que GLOVO es una compañía tecnológica con sede en Barcelona, cuya actividad principal es el desarrollo y gestión de una plataforma tecnológica mediante la que a través de una aplicación móvil o de una web (en Adelante, la <strong>APP</strong>) permite a determinadas tiendas locales de algunas ciudades ofertar sus productos a través de la misma.</p>
            <p>II.     Que el <strong>PARTNER</strong> está interesado en poner a disposición los productos y/o servicios que ofrece en su comercio para que puedan ser ofertados a través de la APP, y así beneficiarse de todos los usuarios de la <strong>APP</strong>.</p>
            <p>III.     Que, las Partes convienen que el pago por el uso de la APP por parte del PARTNER será variable y se calculará utilizando como base las ventas brutas de productos y/o servicios obtenidos por el PARTNER como consecuencia del uso de la APP, y se calculará en base a 30 % sobre las mismas + el IVA correspondiente (en adelante, el PRECIO).</p>
            <p>IV.     Que, el presente contrato integra en su totalidad los "Términos y Condiciones para PARTNERS" adjuntas que serán de aplicación con exclusion de cualquier otra condición, salvo que expresamente en el reverse del presente documento conste alguna especialidad que deberá prevalecer a lo estipulado en los citados Términos y Condiciones.</p>
            <p>V.     En muestra de conformidad con el presente Contrato, y con los “Términos y Condiciones para PARTNERS de GLOVO”, los cuales el PARTNER manifiesta haber leído y aceptado, las Partes firman el presente Contrato en la fecha y lugar indicado en el encabezado del presente.</p>
            <br/>
            <h4>TÉRMINOS Y CONDICIONES PARTNERS GLOVO</h4>
            <p>A través de los presentes términos y condiciones generales de uso e información legal (en adelante, los Términos y Condiciones del Partner), Glovoapp Spain Platform, S.L.U. (en adelante, GLOVO) pone a disposición de los Partners (en adelante PARTNER o PARTNERS) el sitio web, cuyo dominio es www.glovoapp.com, y la aplicación móvil Glovo (en adelante denominadas conjuntamente, la APP). Estos Términos y Condiciones Generales del Partner se aplican al uso de la Plataforma por parte del PARTNER, así como a todos sus sitios relacionados o vinculados desde www.glovoapp.com por GLOVO (en adelante y de forma conjunta, el «sitio»). El sitio es propiedad de GLOVO. Al utilizar el sitio, estás conforme con las presentes condiciones de uso. Si no estás de acuerdo, te rogamos te abstengas de utilizarlo.</p>
            <p>A los efectos de los presentes Términos y Condiciones del Partner, los términos siguientes, que se identifican con letra mayúscula, tendrán el significado que se especifica a continuación:</p>
            <p>Servicios de Marketplace: intermediación tecnológica en la puesta a disposición de los productos y/o servicios que el PARTNER ofrece a través de la APP de GLOVO y entrega a los usuarios de la APP de GLOVO utilizando su propia flota de mensajeros.</p>
            <p>Servicios de intermediación de MANDATARIOS: intermediación tecnológica en la puesta a disposición de los productos y/o servicios que el PARTNER ofrece a través de la APP de GLOVO y entrega a los usuarios de la APP de GLOVO utilizando a los mensajeros independientes que prestan servicio a través de la APP de GLOVO (en adelante “MANDATARIO o MANDATARIOS”).</p>
            <p>Denominación social: Glovoapp Spain Platform, S.L.U.</p>
            <p>Domicilio social: C/ Pallars 190, 08005 Barcelona.</p>
            <p>Datos de inscripción en el Registro Mercantil: Protocolo 2021/3871, Tomo: 46614, Folio: 172, Hoja: 525512, Inscripción: 1.</p>
            <p>Número de Identificación Fiscal (NIF): B-67282871</p>
            <br/>
            <p>1.- OBJETO.-</p>
            <p>1.1. Constituye el objeto común de los presentes Términos y Condiciones del Partner la puesta a disposición de los productos y/o servicios que el PARTNER ofrece a través de la APP. GLOVO, a través de la APP: (a) proporciona intermediación tecnológica en la generación de leads y el procesamiento de pagos y otros servicios relacionados con la venta en tienda y la entrega de productos y (b) gestiona incidencias de los pedidos.  El PARTNER será el "minorista", el "proveedor" o el "vendedor" físico de todos los productos, y, para los Servicios de Marketplace, también el responsable de los servicios de entrega relacionados con dichos productos. El PARTNER puede tener diferentes establecimientos o tiendas (en adelante, "AFILIADOS") cuyos detalles deben comunicarse con anticipación a GLOVO para que se activen y habiliten en la APP. Asimismo, el PARTNER puede tener franquiciados que, para cumplir con los presentes Términos y Condiciones del Partner, deben firmar el “Formulario de adhesión de franquiciados” provisto en el Anexo I.</p>
            <p>1.2. Para los PARTNERS que únicamente hagan uso de los Servicios de Marketplace, GLOVO: </p>
            <p>a) No será responsable, en ningún caso, de los servicios de entrega que sean prestados por el PARTNER, junto con su propia flota de mensajeros ni del costo, la capacitación, los seguros, el equipo, los contratos, las obligaciones laborales, las obligaciones tributarias ni cualquier otro tipo de responsabilidad que pueda estar relacionada o que pueda surgir con dicha flota, que será asumida en su totalidad por el PARTNER. </p>
            <p>b) Actuará como agente de cobro de pagos por nombramiento del PARTNER, con el único fin de aceptar los pagos en nombre del PARTNER a través de la funcionalidad de procesamiento de pagos facilitada por un proveedor externo en la APP. El PARTNER acuerda que el pago realizado a GLOVO (o a un afiliado de GLOVO que actúe como agente de GLOVO) se considerará de la misma manera que el pago realizado directamente al PARTNER.  </p>
        </div>
    );
};